export interface ThemeColors {
  primary: string;
  on_primary: string;
  primary_container: string;
  secondary: string;
  background: string;
  surface: string;
  surface_variant: string;
  surface_selected: string;
  on_surface: string;
  on_surface_variant: string;
  outline: string;
  outline_subtle: string;
  error: string;
  accent_name: string;
}

export interface ThemeAura {
  themeName: string;
  subtitle: string;
  quote: string;
  nowPlaying: string;
  nowPlayingArtist: string;
  badgeText: string;
  terminalPromptUser: string;
  ambientEffect: "sakura" | "cybergrid" | "embers" | "scanlines" | "celestial" | "aurora" | "rain" | "matrix" | "minimal";
  accentGlow: string;
}

export interface WallpaperTheme {
  id: string;
  name: string;
  filename: string;
  tag: string;
  colors: ThemeColors;
  aura: ThemeAura;
}

// 100% mathematically extracted using the system's generate-theme.py Material You algorithm
export const WALLPAPER_THEMES: WallpaperTheme[] = [
  {
    id: "nezuko",
    name: "Nezuko Kamado",
    filename: "Nezuko Kamado.webp",
    tag: "Blossom Bloom",
    colors: {
      primary: "#e183c2",
      on_primary: "#121214",
      primary_container: "#401b34",
      secondary: "#d8a5ca",
      background: "#130f12",
      surface: "#1f181d",
      surface_variant: "#2c2028",
      surface_selected: "#401b34",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#412f3b",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Blossom Pink",
    },
    aura: {
      themeName: "Blossom Bloom",
      subtitle: "Demon Slayer · Kimetsu no Yaiba",
      quote: "Humans are to be protected and saved. I will never hurt them.",
      nowPlaying: "Kamado Nezuko no Uta",
      nowPlayingArtist: "Go Shiina ft. Nami Nakagawa",
      badgeText: "Demon Slayer · Blossom Hashira",
      terminalPromptUser: "Krish@Nezuko",
      ambientEffect: "sakura",
      accentGlow: "rgba(225, 131, 194, 0.45)",
    },
  },
  {
    id: "reze",
    name: "Reze",
    filename: "Reze.webp",
    tag: "Host Machine Default",
    colors: {
      primary: "#f3a171",
      on_primary: "#121214",
      primary_container: "#41281a",
      secondary: "#f9c384",
      background: "#13110f",
      surface: "#1f1b18",
      surface_variant: "#2c2420",
      surface_selected: "#41281a",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#41352f",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Amber Flame",
    },
    aura: {
      themeName: "Bomb Devil",
      subtitle: "Chainsaw Man · Soviet Assassin",
      quote: "Do you know how to swim, Denji?",
      nowPlaying: "Jane Doe (Reze Theme)",
      nowPlayingArtist: "Chainsaw Man OST",
      badgeText: "Host Machine Default · Bomb Devil",
      terminalPromptUser: "Krish@Reze",
      ambientEffect: "embers",
      accentGlow: "rgba(243, 161, 113, 0.45)",
    },
  },
  {
    id: "luffy",
    name: "Gear5 Luffy",
    filename: "Gear5 Luffy.webp",
    tag: "Electric Nika",
    colors: {
      primary: "#71d9f3",
      on_primary: "#121214",
      primary_container: "#193941",
      secondary: "#aee6f4",
      background: "#0f1313",
      surface: "#171f20",
      surface_variant: "#1f2a2c",
      surface_selected: "#193941",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#2e3f42",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Sun God Cyan",
    },
    aura: {
      themeName: "Sun God Nika",
      subtitle: "One Piece · Drums of Liberation",
      quote: "This is my peak! As long as I am alive, the possibilities are limitless!",
      nowPlaying: "Overtaken · Drums of Liberation",
      nowPlayingArtist: "Kohei Tanaka",
      badgeText: "Warrior of Liberation · Gear 5",
      terminalPromptUser: "Krish@Nika",
      ambientEffect: "celestial",
      accentGlow: "rgba(113, 217, 243, 0.45)",
    },
  },
  {
    id: "shinobu",
    name: "Shinobu Kochō",
    filename: "Shinobu Kochō v4.0.webp",
    tag: "Wisteria Mist",
    colors: {
      primary: "#b4b7ed",
      on_primary: "#121214",
      primary_container: "#2b2c40",
      secondary: "#cad1f3",
      background: "#0f0f13",
      surface: "#181820",
      surface_variant: "#21222c",
      surface_selected: "#2b2c40",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#333543",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Wisteria Indigo",
    },
    aura: {
      themeName: "Insect Hashira",
      subtitle: "Demon Slayer · Butterfly Dance",
      quote: "I may be the only swordsman among the Hashira who cannot cut off a demon's head.",
      nowPlaying: "Kochou Shinobu Theme",
      nowPlayingArtist: "Yuki Kajiura",
      badgeText: "Insect Hashira · Wisteria Bloom",
      terminalPromptUser: "Krish@Shinobu",
      ambientEffect: "aurora",
      accentGlow: "rgba(180, 183, 237, 0.45)",
    },
  },
  {
    id: "bluegirl",
    name: "Blue Girl",
    filename: "Blue Girl.webp",
    tag: "Frost Azure",
    colors: {
      primary: "#71caf3",
      on_primary: "#121214",
      primary_container: "#183541",
      secondary: "#9cd6f2",
      background: "#0f1213",
      surface: "#171e20",
      surface_variant: "#1f292c",
      surface_selected: "#183541",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#2e3e43",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Frost Blue",
    },
    aura: {
      themeName: "Frost Azure",
      subtitle: "Glacial Serenity · Cyberspace",
      quote: "Silence is the purest frequency in the matrix.",
      nowPlaying: "Resonance",
      nowPlayingArtist: "HOME",
      badgeText: "Glacial Cyber · Deep Frost",
      terminalPromptUser: "Krish@Azure",
      ambientEffect: "rain",
      accentGlow: "rgba(113, 202, 243, 0.45)",
    },
  },
  {
    id: "makima",
    name: "Makima",
    filename: "Makima.webp",
    tag: "Control Velvet",
    colors: {
      primary: "#f3a971",
      on_primary: "#121214",
      primary_container: "#412b1a",
      secondary: "#f5c596",
      background: "#13110f",
      surface: "#201a17",
      surface_variant: "#2c2420",
      surface_selected: "#412b1a",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#41362e",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Velvet Ochre",
    },
    aura: {
      themeName: "Control Devil",
      subtitle: "Public Safety Devil Hunter Special Division 4",
      quote: "All devils are born with a name. The more that name is feared, the more powerful the devil.",
      nowPlaying: "Sweet Dreams (Are Made of This)",
      nowPlayingArtist: "Eurythmics",
      badgeText: "Control Devil · Public Safety",
      terminalPromptUser: "Krish@Makima",
      ambientEffect: "embers",
      accentGlow: "rgba(243, 169, 113, 0.45)",
    },
  },
  {
    id: "sword",
    name: "Sword Silver Hair",
    filename: "Sword Silver Hair.webp",
    tag: "Katana Crimson",
    colors: {
      primary: "#f58a8c",
      on_primary: "#121214",
      primary_container: "#411d1e",
      secondary: "#f4a7a8",
      background: "#130f0f",
      surface: "#1f1818",
      surface_variant: "#2c2020",
      surface_selected: "#411d1e",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#422f30",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Blade Rose",
    },
    aura: {
      themeName: "Blade Crimson",
      subtitle: "Iaijutsu Master · Scarlet Edge",
      quote: "A single draw cuts down shadow and steel alike.",
      nowPlaying: "The Last Shuriken",
      nowPlayingArtist: "Hiroyuki Sawano",
      badgeText: "Blade Master · Scarlet Katana",
      terminalPromptUser: "Krish@Katana",
      ambientEffect: "matrix",
      accentGlow: "rgba(245, 138, 140, 0.45)",
    },
  },
  {
    id: "wall",
    name: "Wall Gold",
    filename: "Wall.webp",
    tag: "Golden Minimal",
    colors: {
      primary: "#f2e2b0",
      on_primary: "#121214",
      primary_container: "#413b2c",
      secondary: "#eee1be",
      background: "#13120f",
      surface: "#1f1d18",
      surface_variant: "#2c2820",
      surface_selected: "#413b2c",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#423d30",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Warm Aurum",
    },
    aura: {
      themeName: "Golden Architecture",
      subtitle: "Minimalist Geometry · Sunlit Ochre",
      quote: "Structure, symmetry, and the quiet beauty of light.",
      nowPlaying: "Experience",
      nowPlayingArtist: "Ludovico Einaudi",
      badgeText: "Minimal Aurum · Golden Ratio",
      terminalPromptUser: "Krish@Architect",
      ambientEffect: "minimal",
      accentGlow: "rgba(242, 226, 176, 0.45)",
    },
  },
  {
    id: "neon",
    name: "Japanese Neon",
    filename: "Japanese Neon.webp",
    tag: "Tokyo Dusk",
    colors: {
      primary: "#d490b1",
      on_primary: "#121214",
      primary_container: "#3a212d",
      secondary: "#d5a8be",
      background: "#131011",
      surface: "#1f181b",
      surface_variant: "#2a2126",
      surface_selected: "#3a212d",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#3e3137",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Dusk Mauve",
    },
    aura: {
      themeName: "Neo Tokyo Synth",
      subtitle: "Cyberpunk Nightscape · Shinjuku D-Bus",
      quote: "Neon reflections across wet asphalt and high-voltage dreams.",
      nowPlaying: "I Really Want to Stay At Your House",
      nowPlayingArtist: "Rosa Walton",
      badgeText: "Neo Tokyo · Cyberpunk Synthwave",
      terminalPromptUser: "Krish@NeoTokyo",
      ambientEffect: "cybergrid",
      accentGlow: "rgba(212, 144, 177, 0.45)",
    },
  },
  {
    id: "wings",
    name: "Wings Dark",
    filename: "Wings Dark.webp",
    tag: "Abyssal Coral",
    colors: {
      primary: "#ec7883",
      on_primary: "#121214",
      primary_container: "#3e181c",
      secondary: "#ea9da4",
      background: "#130f10",
      surface: "#1f1819",
      surface_variant: "#2b2022",
      surface_selected: "#3e181c",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#402f32",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Coral Night",
    },
    aura: {
      themeName: "Abyssal Seraph",
      subtitle: "Dark Angel · Crimson Wings",
      quote: "From the abyss rises the darkest wings of twilight.",
      nowPlaying: "Midnight City",
      nowPlayingArtist: "M83",
      badgeText: "Abyssal Seraph · Midnight Coral",
      terminalPromptUser: "Krish@Seraph",
      ambientEffect: "celestial",
      accentGlow: "rgba(236, 120, 131, 0.45)",
    },
  },
  {
    id: "lain",
    name: "Lain",
    filename: "Lain.webp",
    tag: "Wired Phosphor",
    colors: {
      primary: "#e296b3",
      on_primary: "#121214",
      primary_container: "#3d202c",
      secondary: "#ddb3c3",
      background: "#130f11",
      surface: "#1f181a",
      surface_variant: "#2b2125",
      surface_selected: "#3d202c",
      on_surface: "#FFFFFF",
      on_surface_variant: "#A5A5AA",
      outline: "#3f3037",
      outline_subtle: "#25252a",
      error: "#FF6B6B",
      accent_name: "Wired Rose",
    },
    aura: {
      themeName: "Wired Entity",
      subtitle: "Serial Experiments Lain · Copland OS",
      quote: "No matter where you go, everyone is always connected.",
      nowPlaying: "Duvet",
      nowPlayingArtist: "Bôa",
      badgeText: "The Wired · Copland OS Enterprise",
      terminalPromptUser: "Krish@Wired",
      ambientEffect: "scanlines",
      accentGlow: "rgba(226, 150, 179, 0.45)",
    },
  },
];
